sudo: required # disables container-based builds which have a maximum of 4GB of memory
language: android
jdk: oraclejdk8
env:
  global:
    - ADB_INSTALL_TIMEOUT=15 # wait up to 15 minutes for adb to connect to emulator (2 minutes by default)
    - EMULATOR_ANDROID_VERSION=19
    - BUILD_ANDROID_VERSION=28
    - BUILD_TOOLS_VERSION=28.0.3
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
android:
 components:
    - tools # to get the new `repository-11.xml`
    - tools # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-$BUILD_TOOLS_VERSION
    - android-$BUILD_ANDROID_VERSION
    - android-$EMULATOR_ANDROID_VERSION
    - sys-img-armeabi-v7a-android-$EMULATOR_ANDROID_VERSION
licenses:
  - 'android-sdk-license-.+'
before_install:
  # List all available targets, device definitions and AVDs.
  - sdkmanager --list || true

  # Update sdk tools to latest version and install/update components
  - yes | sdkmanager "tools" > /dev/null
  - yes | sdkmanager "platform-tools" > /dev/null
  - yes | sdkmanager "build-tools;$BUILD_TOOLS_VERSION" > /dev/null

  - yes | sdkmanager "platforms;android-$EMULATOR_ANDROID_VERSION" > /dev/null
  - yes | sdkmanager "platforms;android-$BUILD_ANDROID_VERSION" > /dev/null

#  - yes | sdkmanager "system-images;android-24;google_apis;armeabi-v7a" > /dev/null

  - yes | sdkmanager --update > /dev/null
  - yes | sdkmanager --licenses > /dev/null

  # Check components status
  - sdkmanager --list || true

before_script:
  # local.properties file is not checked in but required (an empty file is good enough)
  - touch local.properties

  # Make sure gradlew is executable
  - chmod +x gradlew

  # Create emulator and wait for it to start
  - sdkmanager "system-images;android-$EMULATOR_ANDROID_VERSION;google_apis;armeabi-v7a"
  - echo no | avdmanager -v create avd -f -n test -k "system-images;android-$EMULATOR_ANDROID_VERSION;google_apis;armeabi-v7a"
  # Use new emulator executable location
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

  # Turn off animations
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &

  # Wake up
  - adb shell input keyevent 82 &
  - adb shell input keyevent 1 &

script:
  - ./gradlew clean test --stacktrace

# Simpler config, but less up-to-date when it comes to tooling.
# Added here for historical reasons.
# language: android
# jdk: oraclejdk8
# android:
#   components:
#   - tools
#   - platform-tools
#   - build-tools-28.0.3
#   - android-28
#   - android-24
#   - sys-img-armeabi-v7a-android-24
# licenses:
# - 'android-sdk-license-.+'
# before_install:
# - yes | sdkmanager "platforms;android-24"
# - yes | sdkmanager "platforms;android-28"
# - yes | sdkmanager "build-tools;28.0.3"
# before_script:
# local.properties file is not checked in but required (an empty file is good enough)
# - touch local.properties

# Make sure gradlew is executable
# - chmod +x gradlew

# Create emulator and wait for it to start
# - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
# - emulator -avd test -no-skin -no-window &
# - android-wait-for-emulator
# - adb shell input keyevent 82 &

# before_cache:
#   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
# cache:
#   directories:
#     - $HOME/.gradle/caches/
#     - $HOME/.gradle/wrapper/
#     - $HOME/.android/build-cache
# script:
# - ./gradlew clean test --stacktrace